### ISSUE TITLE
Encrypt user share when creating new dwallet

### ISSUE THREAD

**Issue by yaelAbergel** [dwallet-labs/dwallet-network#163]

**Comment by ycscaly** [comment]
Please remember:
`When you create the dWallet, you just did DKG with the blockchain. So you have your own DKG output (the centralized_party::dkg::Output), and you can make sure the values are the same as the one saved on the blockchain (the decentralized_party::dkg::Output). After you do, it is safe to sign.`

**Comment by ItayLevyOfficial** [comment]
moved to https://github.com/dwallet-labs/dwallet-network/issues/175
