### ISSUE TITLE
dwallet-network: handle pending MPC events in `pending_instances_queue`

### ISSUE THREAD

**Issue by zeevmoney** [dwallet-labs/dwallet-network#307]

**Comment by cdesaintguilhem** [comment]
Notes from meeting on November 4th:

1. The check before adding to the queue should also check whether the queue is not empty, to prevent an instance from "cutting the queue". 
   Alternatively, _every_ instance could be added to the queue when it is given to the MPC Manager, and there is a separate part of the code that pops from the queue when there are not enough active instances.
2. The current code doesn't "clean up" finished instances and pop new ones from the queue.
