### ISSUE TITLE
dwallet-network: change MPC output TX creation party to be dynamic

### ISSUE THREAD

**Issue by zeevmoney** [dwallet-labs/dwallet-network#308]
Currently this is hardcoded to 3, should decide on a mechanism to do it.

**Comment by zeevmoney** [comment]
![Image](https://github.com/user-attachments/assets/c29a28a9-5611-4ed7-98a3-e347e5a771d8)

**Comment by cdesaintguilhem** [comment]
Before deciding on a new mechanism, see [this function](https://github.com/dwallet-labs/dwallet-network/blob/a144c6b1878dccd3f4bd025e6829179236bf07a7/crates/sui-core/src/consensus_adapter.rs#L498-L562).
