### ISSUE TITLE
Allow users to verify and store their sign part on chain

### ISSUE THREAD

**Issue by ItayLevyOfficial** [dwallet-labs/dwallet-network#358]

**Comment by zeevmoney** [comment]
Why? are you sure that we need it? was it implemented in the previous code?

**Comment by zeevmoney** [comment]
We need to talk about this one before starting it.

**Comment by ItayLevyOfficial** [comment]
we need this in order to implement future transactions - i.e. a transaction a user should agree to sign on before the blockchain, based on some other logic, agrees to sign on
